language: ruby
cache: bundler
dist: trusty

sudo: false

branches:
  only:
    - master
    - 13-stable

before_install:
  - gem --version
  - rvm @global do gem uninstall bundler -a -x -I || true
  - gem install bundler
  - bundle --version
  - rm -f .bundle/config
rvm:
  - 2.4.2
  - 2.5.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - bundle exec chefstyle
  - bundle exec rake spec
  - bundle exec ohai
