language: ruby
cache: bundler
dist: trusty

sudo: false

branches:
  only:
    - master
    - 8-stable

before_install:
  - gem update --system
  - gem --version
  - rvm @global do gem uninstall bundler -a -x -I
  - gem install bundler -v 1.14.6
  - bundle --version
  - rm -f .bundle/config
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

allow_failures:
  - rvm: ruby-head

script:
  - bundle exec chefstyle
  - bundle exec rake spec
  - bundle exec ohai
