language: ruby
cache: bundler
dist: xenial
sudo: false

branches:
  only:
    - master
    - 14-stable
    - 13-stable

bundler_args: --jobs 7 --without docs debug

before_install:
  - gem --version
  - rvm @global do gem uninstall bundler -a -x -I || true
  - gem install bundler
  - bundle --version
  - rm -f .bundle/config
rvm:
  - 2.4.5
  - 2.5.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - bundle exec chefstyle -v
  - bundle exec rake
  - bundle exec ohai
