version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

environment:
  matrix:
    - ruby_version: "25"

clone_folder: c:\projects\ohai
clone_depth: 1

skip_commits:
  # version bumps by Expeditor happen as a separate commit after the merge, we can skip
  author: Chef Expeditor
  # if ONLY the files listed below are changed in a commit, skip
  files:
    - MAINTAINERS.md
    - MAINTAINERS.toml
    - CHANGELOG.md
    - RELEASE_NOTES.md

skip_tags: true
branches:
  only:
    - master
    - 14-stable
    - 13-stable

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - bundler --version

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - bundle exec rspec
  - bundle exec ohai
