version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

environment:
  matrix:
    - ruby_version: "24"  

clone_folder: c:\projects\ohai
clone_depth: 1
skip_tags: true
branches:
  only:
    - master
    - 13-stable

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - bundler --version

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - bundle exec rspec
  - bundle exec ohai
