name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master
pr:
- master

pool:
  vmImage: 'Ubuntu 16.04'
strategy:
  matrix:
    ruby 2.3:
      ruby_version: '2.3'
    ruby 2.4:
      ruby_version: '2.4'
    ruby 2.5:
      ruby_version: '2.5'
    ruby 2.6:
      ruby_version: '2.6'
steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: $(ruby_version)
- script: ruby --version
